[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }

[window]
option_as_alt = "Both"

[[hints.enabled]]
regex = "(^|[\\s\"'`(\\[])(/|~/)[\\w./\\-]+(:\\d+(:\\d+)?)?"
command = { program = "/Users/peter/.local/bin/alacritty-tmux-nvim", args = [] }
post_processing = true
persist = false
mouse = { enabled = true, mods = "Control" }
binding = { key = "F", mods = "Control|Shift" }
