[accounts.emponaut]
default = true
email = "peter@emponaut.com"
display-name = "Peter McEvoy"
downloads-dir = "/tmp"
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "peter@emponaut.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = 'op read "op://Employee/Google/Himalaya app password"'
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.login = "peter@emponaut.com"
message.send.backend.encryption.type = "tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = 'op read "op://Employee/Google/Himalaya app password"'
