case $(uname -s) in
  "Darwin")
    export ANDROID_HOME="$HOME/Library/Android/sdk"
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
    export PATH="/opt/homebrew/bin:$PATH"
    export PATH="$PATH:$ANDROID_HOME/emulator"
    export PATH="$PATH:$ANDROID_HOME/platform-tools"
    ;;
  "Linux")
    # see https://forums.ankiweb.net/t/anki-doesnt-start-under-wayland-linux/10409
    export QT_QPA_PLATFORM=xcb
    export XDG_CURRENT_DESKTOP="sway"
    ;;
esac
export GOPATH="$(go env GOPATH)"
export PATH="$GOPATH/bin:$NVM_BIN:$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

export EDITOR=$(which nvim)
export FZF_DEFAULT_COMMAND="fd --hidden --no-ignore"
export FZF_DEFAULT_OPTS="--cycle --keep-right --multi"
export GIT_AUTHOR_EMAIL="git@mcevoypeter.com"
export GIT_AUTHOR_NAME="Peter McEvoy"
export GIT_COMMITTER_EMAIL="git@mcevoypeter.com"
export GIT_COMMITTER_NAME="Peter McEvoy"
export GNUPGHOME="$HOME/.gnupg/trezor"
# Increase speed of key timeouts.
export KEYTIMEOUT=1

# from https://github.com/nvm-sh/nvm#git-install
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PYENV_ROOT="$HOME/.pyenv"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/ripgreprc"
export TERM="tmux-256color"
